spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_data_jpa?serverTimezone=UTC
    username: root
    password: root
  jpa:
    generate-ddl: true
    database: mysql
#    hibernate:
#      ddl-auto: create
